# -*- coding: utf-8 -*-
"""Copy of listsFunctions&ForLoopsPart2.py_Zachary Barner.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T2CyIkigBSg32mWUVmEZVEre2ssd4psB

# **SECTION A - Complete ALL 4 functions**

```
Function 1: Write a function called count_evens(values) that accepts a list of ints
as a parameter and returns the number of even ints in the given list. Note: the %
"mod" operator computes the remainder, e.g. 5 % 2 is 1.
count_evens([2, 1, 2, 3, 4]) → 3
count_evens([2, 2, 0]) → 3
count_evens([1, 3, 5]) → 0
```
"""

def count_evens(values):
  total = 0
  for i in values:
    if i % 2 == 0:
      total += 1
  print(total)

count_evens([2, 1, 2, 3, 4])
count_evens([2, 2, 0])
count_evens([1, 3, 5])

"""```
Function 2: Write a function called contains_string(values, str) that accepts a
list of strings and another string as parameters and returns True if the list
contains the given string and false otherwise.
contains_string(['hello', 'cats', 'dogs'], 'cats') → True
contains_string(['hello', 'cats', 'dogs'], 'cat') → False
contains_string(['a', 'b', 'c'], 'd') → False
```
"""

def contains_string(values, string):
  if string in values:
    return True
  else:
    return False

print(contains_string(['hello', 'cats', 'dogs'], 'cats'))
print(contains_string(['hello', 'cats', 'dogs'], 'cat'))
print(contains_string(['a', 'b', 'c'], 'd'))

"""```
Function 3: Write a function called count_lengths(values, length) that accepts a
list of strings and an int as parameters and returns the number of strings in the
list that are exactly the given length.
count_lengths(['a', 'b', 'c'], 2) → 0
count_lengths(['a', 'aa', 'aaa'], 3) → 1
count_lengths(['cat', 'dog', 'bird'], 3) → 2
```
"""

from re import I
def count_lengths(values, length):
  givenLength = 0
  for i in values:
    if length == len(i):
      givenLength += 1
  print(givenLength)

count_lengths(['a', 'b', 'c'], 2)
count_lengths(['a', 'aa', 'aaa'], 3)
count_lengths(['cat', 'dog', 'bird'], 3)

"""

```
Function 4: Write a function called match_up(list1, list2) that takes two lists as
parameters.
Given list1 and list2 of the same length, for every element in the first list,
consider the corresponding element in the other list(at the same index). Return the
count of the number of times that the two elements are not equal to each other.
match_up([1, 2, 3], [1, 2, 3]) → 0
match_up([1, 2, 3], [2, 3, 5]) → 3
match_up([1, 2, 3], [3, 3, 3]) → 2
'''```

"""

def match_up(list1, list2):
  matchNum = 0
  for i in range(len(list1)):
    if list1[i] != list2[i]:
      matchNum += 1
  print(matchNum)

match_up([1, 2, 3], [1, 2, 3])
match_up([1, 2, 3], [2, 3, 5])
match_up([1, 2, 3], [3, 3, 3])

"""# **SECTION B - Pick 1 Function **

```
Function 5: Write a function called make_list(length, num) that accepts two int
parameters and returns a new list that is length (the first input) elements long
that is filled with num (the second input). You can do this manually using a loop
or there’s a way to do this with a bit of built-in Python syntax. Write the
function twice, using both ways!
make_list(1, 9) → [9]
make_list(3, 1) → [1, 1, 1]
make_list(5, 0) → [0, 0, 0, 0, 0]

```
"""



"""

```
Function 6: Write a function called reverse(values) that accepts a list as a
parameter and returns a new list that is made up of the elements of the parameter
list in reverse order. You can do this manually using a loop or there’s a way to do
this with a built-in Python function. Again, do it both ways!
reverse([1, 2, 3]) → [3, 2, 1]
reverse(['a', 'b', 'c', 'd']) → ['d', 'c', 'b', 'a']
reverse([1, 100]) → [100, 1]
```



"""



"""

```
Function 7: Write a function called get_alternating(values, evens) that accepts two
parameters: a list of values and a boolean. If the boolean “evens” is true, return
a new list that is made up of the even index elements of the parameter list only.
If the boolean is, return a new list that contains only the odd index elements. You
can do this manually using a loop or there’s a way to do this with built in Python
syntax. Again, do it both ways!
get_alternating([1, 2, 3, 4, 5], true) → [1, 3, 5]
get_alternating([1, 2, 3, 4, 5], false) → [2, 4]
get_alternating(['cat', 'dog', 'frog'], true) → ['cat', 'frog']```

"""



"""```
Function 8: Write a function called get_filtered(values, limit) that accepts two
parameters: a list of integer values and a single int. Based on the “limit” int
parameter, return a new list that contains only the elements in the initial list
that are less than or equal to the “limit”. Again, find multiple ways to write this
function to compare alternate ways!
get_filtered([1, 2, 3, 4, 5], 10) → [1, 2, 3, 4, 5]
get_filtered([10, 9, 8, 7], 8) → [7, 8]
get_filtered([19, 40, 21, 11, 80], 5) → []
```
"""

#way #1
def get_filtered(values, limit):
  newlist = []
  for value in values:
    if value <= limit:
      newlist.append(value)
  print(newlist)

get_filtered([10, 9, 8, 7], 8)
get_filtered([19, 40, 21, 11, 80], 5)
get_filtered([1, 2, 3, 4, 5], 10)

#way #2
def get_filtered2(values, limit):
  newlist = []
  while len(values) > 0:
    smallest = min(values)
    if smallest > limit:
      values.remove(smallest)
    else:
      newlist.append(smallest)
      values.remove(smallest)
  print(newlist)

get_filtered2([10, 9, 8, 7], 8)
get_filtered2([19, 40, 21, 11, 80], 5)
get_filtered2([1, 2, 3, 4, 5], 10)